Algoritmo "Calcular seno de um angulo"
// Disciplina   : Algoritmos - Curso em Vídeo
// Professor   : Gustavo Guanabara
// Descrição   : Exercícios de estruturas condicionais
// Autor(a)    : Leonardo Zanoni
// Data atual  : 23/12/2021
Var
   Angulo, S: Real

Inicio
      Escreva("Informe um angulo:")
      Leia(Angulo)
      S <- Sen(GraupRad(Angulo))
      Escreva(" O seno de ", Angulo, " e igual a",S)

Fimalgoritmo