Algoritmo "CONDICAOPARACONTAGEMREGRESSIVAVALORESPARES"
// Disciplina   : Algoritmos - Curso em Vídeo
// Professor   : Gustavo Guanabara
// Descrição   : Exercícios
// Autor(a)    : Leonardo Zanoni
// Data atual  : 28/12/2021
Var
   CONT, V: Inteiro


Inicio
      Escreva("DIGITE UM VALOR ")
      Leia(V)
      Se(V%2= 1)entao
         V <- V - 1
      FimSe
      Para CONT <- V ate 0 passo -2 faca
           Escreval(CONT)
      FimPara
      

Fimalgoritmo