Algoritmo "Descobrir a idade"
// Disciplina   : Algoritmos - Curso em Vídeo
// Professor   : Gustavo Guanabara
// Descrição   : Exercícios
// Autor(a)    : Leonardo Zanoni
// Data atual  : 25/12/2021

Var
   ANO_ATUAL, ANO_NASC, IDADE: Inteiro
   
Inicio
      Escreva("Digite o ano atual ")
      Leia(ANO_ATUAL)
      Escreva("Digite o ano de nascimento ")
      Leia(ANO_NASC)
      IDADE <- (ANO_ATUAL - ANO_NASC)
      Escreval(" Sua idade e de : ", IDADE, " anos")
      

Fimalgoritmo