Algoritmo "FAZSOMAPROCEDIMENTO"
// Disciplina   : Algoritmos - Curso em Vídeo
// Professor   : Gustavo Guanabara
// Descrição   : Exercícios
// Autor(a)    : Leonardo Zanoni
// Data atual  : 29/12/2021
Var
   X, Y: Inteiro
   
Procedimento Soma(A, B: Inteiro)
Inicio
      Escreval("RECEBI O VALOR ",A)
      Escreval("RECEBI O VALOR ",B)
      Escreval("A SOMA ENTRE OS DOIS E ", A + B)

FimProcedimento

Inicio
      X <- 5
      Y <- 3
      SOMA(X, Y)

Fimalgoritmo