Algoritmo "TesteVetor"
// Disciplina   : Algoritmos - Curso em Vídeo
// Professor   : Gustavo Guanabara
// Descrição   : Exercícios
// Autor(a)    : Leonardo Zanoni
// Data atual  : 02/01/2022
Var
   v: vetor [1..6] de Inteiro
   c: Inteiro

Inicio
      Para c <- 1 ate 6 faca
           Escreva("DIGITE O, ", c, " o VALOR")
           Leia(v[c])
      FimPara

      Para c <- 1 ate 6 faca
           Escreva("{", v[c], "}")
      FimPara
      
Fimalgoritmo